title: openbookstudio
url: https://openbookstudio.github.io
baseurl: 

author: Eliana Yeom, pleasing_aroma
description: Following the path of the light.

include: ['_pages']

collections_dir: series

collections:
  home:
    output: true
  
  childrenliterature:
    output: true

  kkomi:
    output: true

  shion:
    output: true

  snap:
    output: true
  
  ai_influencer:
    output: true
  
  photorestoration:
    output: true
  
  ai_memorymovie:
    output: true

markdown: kramdown
kramdown:
  input: GFM
