title: openbookstudio
url: https://openbookstudio.github.io/
baseurl: 

author: Eliana Yeom, pleasing_aroma
description: Following the path of the light.

include: ['_pages']

collections_dir: series

collections:
  home:
    output: true
  kochi:
    output: true
  london:
    output: true
  rimi:
    output: true
  cn_fishnet:
    output: true
  photorestoration:
    output: true
markdown: kramdown
kramdown:
  input: GFM
